Greeting.create(message: "Welcome to our App!")
Greeting.create(message: "Bienvenid@ a nuestra App!")
Greeting.create(message: "You ever wondered, what's going inside their head?")
Greeting.create(message: "Now playing: Laplace's Angel - Will Wood")
Greeting.create(message: "The trees deny themselves nothing that makes them grow")